kind: Namespace 
apiVersion: v1 
metadata:
  name: prueba
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: prueba
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    role: php-apache