apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: hpa-demo-deployment
 namespace: prueba
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: hola-deploy
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50 