apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hola-deploy
  namespace: prueba
  labels:
    app:  hola
spec:
  selector:
    matchLabels:
      app: hola
  replicas: 1
  template:
    metadata:
      labels:
        app:  hola
    spec:
      containers:
      - name:  hola
        image:  pbitty/hello-from:latest
        resources:
          requests:
            cpu: 20m
            memory: 10Mi
          limits:
            cpu: 30m
            memory: 15Mi
        ports:
        - containerPort:  80